//
// ExplosionView.h
// Generated by Core Animator version 1.0 on 3/12/15.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import <UIKit/UIKit.h>

IB_DESIGNABLE
@interface ExplosionView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// explode
- (void)addExplodeAnimation;
- (void)addExplodeAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addExplodeAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addExplodeAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addExplodeAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeExplodeAnimation;

- (void)removeAllAnimations;

@end