//
// ExplosionView.m
// Generated by Core Animator version 1.0 on 3/12/15.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import "ExplosionView.h"

@interface ExplosionView ()
@property (strong, nonatomic) NSMapTable *completionBlocksByAnimation;
@end

@implementation ExplosionView

#pragma mark - Life Cycle

- (instancetype)init
{
	return [self initWithFrame:CGRectMake(0,0,120,120)];
}

- (instancetype)initWithFrame:(CGRect)frame
{
	self = [super initWithFrame:frame];
	if (self)
	{
		[self setupHierarchy];
	}
	return self;
}

- (instancetype)initWithCoder:(NSCoder *)coder
{
	self = [super initWithCoder:coder];
	if (self)
	{
		[self setupHierarchy];
	}
	return self;
}

#pragma mark - Scaling

- (void)layoutSubviews
{
	[super layoutSubviews];

	UIView *scalingView = self.viewsByName[@"__scaling__"];
	float xScale = self.bounds.size.width / scalingView.bounds.size.width;
	float yScale = self.bounds.size.height / scalingView.bounds.size.height;
	switch (self.contentMode) {
		case UIViewContentModeScaleToFill:
			break;
		case UIViewContentModeScaleAspectFill:
		{
			float scale = MAX(xScale, yScale);
			xScale = scale;
			yScale = scale;
			break;
		}
		default:
		{
			float scale = MIN(xScale, yScale);
			xScale = scale;
			yScale = scale;
			break;
		}
	}
	scalingView.transform = CGAffineTransformMakeScale(xScale, yScale);
	scalingView.center = CGPointMake(CGRectGetMidX(self.bounds), CGRectGetMidY(self.bounds));
}

#pragma mark - Setup

- (void)setupHierarchy
{
	self.completionBlocksByAnimation = [NSMapTable mapTableWithKeyOptions:NSPointerFunctionsOpaqueMemory valueOptions:NSPointerFunctionsStrongMemory];
	NSMutableDictionary *viewsByName = [NSMutableDictionary dictionary];
	NSBundle *bundle = [NSBundle bundleForClass:[self class]];

	UIView *__scaling__ = [UIView new];
	__scaling__.bounds = CGRectMake(0, 0, 120, 120);
	__scaling__.center = CGPointMake(60.0, 60.0);
	[self addSubview:__scaling__];
	viewsByName[@"__scaling__"] = __scaling__;

	UIImageView *whitePuff10 = [UIImageView new];
	whitePuff10.bounds = CGRectMake(0, 0, 174.0, 208.0);
	UIImage *imgWhitePuff10 = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"whitePuff10.png" ofType:nil]];
	whitePuff10.image = imgWhitePuff10;
	whitePuff10.contentMode = UIViewContentModeCenter;
	whitePuff10.layer.position = CGPointMake(60.000, 60.000);
	whitePuff10.alpha = 0.00;
	whitePuff10.transform = CGAffineTransformMakeScale(0.00, 0.00);
	[__scaling__ addSubview:whitePuff10];
	viewsByName[@"whitePuff10"] = whitePuff10;

	UIImageView *whitePuff11 = [UIImageView new];
	whitePuff11.bounds = CGRectMake(0, 0, 203.0, 185.0);
	UIImage *imgWhitePuff11 = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"whitePuff11.png" ofType:nil]];
	whitePuff11.image = imgWhitePuff11;
	whitePuff11.contentMode = UIViewContentModeCenter;
	whitePuff11.layer.position = CGPointMake(60.000, 60.000);
	whitePuff11.alpha = 0.00;
	whitePuff11.transform = CGAffineTransformMakeScale(0.00, 0.00);
	[__scaling__ addSubview:whitePuff11];
	viewsByName[@"whitePuff11"] = whitePuff11;

	UIImageView *whitePuff12 = [UIImageView new];
	whitePuff12.bounds = CGRectMake(0, 0, 174.0, 192.0);
	UIImage *imgWhitePuff12 = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"whitePuff12.png" ofType:nil]];
	whitePuff12.image = imgWhitePuff12;
	whitePuff12.contentMode = UIViewContentModeCenter;
	whitePuff12.layer.position = CGPointMake(60.000, 60.000);
	whitePuff12.alpha = 0.00;
	whitePuff12.transform = CGAffineTransformMakeScale(-0.01, -0.01);
	[__scaling__ addSubview:whitePuff12];
	viewsByName[@"whitePuff12"] = whitePuff12;

	UIImageView *whitePuff13 = [UIImageView new];
	whitePuff13.bounds = CGRectMake(0, 0, 183.0, 200.0);
	UIImage *imgWhitePuff13 = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"whitePuff13.png" ofType:nil]];
	whitePuff13.image = imgWhitePuff13;
	whitePuff13.contentMode = UIViewContentModeCenter;
	whitePuff13.layer.position = CGPointMake(60.000, 60.000);
	whitePuff13.alpha = 0.00;
	whitePuff13.transform = CGAffineTransformMakeScale(-0.01, -0.01);
	[__scaling__ addSubview:whitePuff13];
	viewsByName[@"whitePuff13"] = whitePuff13;

	UIView *plusOne = [UIView new];
	plusOne.bounds = CGRectMake(0, 0, 33.3, 20.5);
	plusOne.layer.position = CGPointMake(56.373, 60.000);
	plusOne.alpha = 0.00;
	plusOne.transform = CGAffineTransformMakeScale(0.21, 0.21);
	[__scaling__ addSubview:plusOne];
	viewsByName[@"plusOne"] = plusOne;

	UIImageView *hud1 = [UIImageView new];
	hud1.bounds = CGRectMake(0, 0, 13.0, 18.0);
	UIImage *imgHud1 = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"hud_1.png" ofType:nil]];
	hud1.image = imgHud1;
	hud1.contentMode = UIViewContentModeCenter;
	hud1.layer.position = CGPointMake(26.753, 10.253);
	[plusOne addSubview:hud1];
	viewsByName[@"hud_1"] = hud1;

	UIImageView *hudX = [UIImageView new];
	hudX.bounds = CGRectMake(0, 0, 15.0, 14.0);
	UIImage *imgHudX = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"hud_x.png" ofType:nil]];
	hudX.image = imgHudX;
	hudX.contentMode = UIViewContentModeCenter;
	hudX.layer.position = CGPointMake(10.253, 10.253);
	hudX.transform = CGAffineTransformMakeRotation(0.785);
	[plusOne addSubview:hudX];
	viewsByName[@"hud_x"] = hudX;

	self.viewsByName = viewsByName;
}

#pragma mark - explode

- (void)addExplodeAnimation
{
	[self addExplodeAnimationWithBeginTime:0 andFillMode:kCAFillModeBoth andRemoveOnCompletion:NO completion:NULL];
}

- (void)addExplodeAnimationWithCompletion:(void (^)(BOOL finished))completionBlock
{
	[self addExplodeAnimationWithBeginTime:0 andFillMode:kCAFillModeBoth andRemoveOnCompletion:NO completion:completionBlock];
}

- (void)addExplodeAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion
{
	[self addExplodeAnimationWithBeginTime:0 andFillMode:removedOnCompletion ? kCAFillModeRemoved : kCAFillModeBoth andRemoveOnCompletion:removedOnCompletion completion:NULL];
}

- (void)addExplodeAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock
{
	[self addExplodeAnimationWithBeginTime:0 andFillMode:removedOnCompletion ? kCAFillModeRemoved : kCAFillModeBoth andRemoveOnCompletion:removedOnCompletion completion:completionBlock];
}

- (void)addExplodeAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock
{
	CAMediaTimingFunction *linearTiming = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionLinear];

	if (completionBlock)
	{
		CABasicAnimation *representativeAnimation = [CABasicAnimation animationWithKeyPath:@"not.a.real.key"];
		representativeAnimation.duration = 1.000;
		representativeAnimation.delegate = self;
		[self.layer addAnimation:representativeAnimation forKey:@"Explode"];
		[self.completionBlocksByAnimation setObject:completionBlock forKey:[self.layer animationForKey:@"Explode"]];
	}

	CAKeyframeAnimation *whitePuff13RotationAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.rotation.z"];
	whitePuff13RotationAnimation.duration = 1.000;
	whitePuff13RotationAnimation.values = @[@(0.000), @(-1.911), @(0.000)];
	whitePuff13RotationAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff13RotationAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff13RotationAnimation.beginTime = beginTime;
	whitePuff13RotationAnimation.fillMode = fillMode;
	whitePuff13RotationAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff13"] layer] addAnimation:whitePuff13RotationAnimation forKey:@"explode_Rotation"];

	CAKeyframeAnimation *whitePuff13OpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	whitePuff13OpacityAnimation.duration = 1.000;
	whitePuff13OpacityAnimation.values = @[@(0.000), @(1.000), @(0.000)];
	whitePuff13OpacityAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff13OpacityAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff13OpacityAnimation.beginTime = beginTime;
	whitePuff13OpacityAnimation.fillMode = fillMode;
	whitePuff13OpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff13"] layer] addAnimation:whitePuff13OpacityAnimation forKey:@"explode_Opacity"];

	CAKeyframeAnimation *whitePuff13ScaleXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.x"];
	whitePuff13ScaleXAnimation.duration = 1.000;
	whitePuff13ScaleXAnimation.values = @[@(-0.010), @(0.150), @(-0.010)];
	whitePuff13ScaleXAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff13ScaleXAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff13ScaleXAnimation.beginTime = beginTime;
	whitePuff13ScaleXAnimation.fillMode = fillMode;
	whitePuff13ScaleXAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff13"] layer] addAnimation:whitePuff13ScaleXAnimation forKey:@"explode_ScaleX"];

	CAKeyframeAnimation *whitePuff13ScaleYAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.y"];
	whitePuff13ScaleYAnimation.duration = 1.000;
	whitePuff13ScaleYAnimation.values = @[@(-0.010), @(0.150), @(-0.010)];
	whitePuff13ScaleYAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff13ScaleYAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff13ScaleYAnimation.beginTime = beginTime;
	whitePuff13ScaleYAnimation.fillMode = fillMode;
	whitePuff13ScaleYAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff13"] layer] addAnimation:whitePuff13ScaleYAnimation forKey:@"explode_ScaleY"];

	CAKeyframeAnimation *whitePuff13TranslationXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.translation.x"];
	whitePuff13TranslationXAnimation.duration = 1.000;
	whitePuff13TranslationXAnimation.values = @[@(0.000), @(-0.000), @(0.000)];
	whitePuff13TranslationXAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff13TranslationXAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff13TranslationXAnimation.beginTime = beginTime;
	whitePuff13TranslationXAnimation.fillMode = fillMode;
	whitePuff13TranslationXAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff13"] layer] addAnimation:whitePuff13TranslationXAnimation forKey:@"explode_TranslationX"];

	CAKeyframeAnimation *whitePuff13TranslationYAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.translation.y"];
	whitePuff13TranslationYAnimation.duration = 1.000;
	whitePuff13TranslationYAnimation.values = @[@(0.000), @(0.000), @(0.000)];
	whitePuff13TranslationYAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff13TranslationYAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff13TranslationYAnimation.beginTime = beginTime;
	whitePuff13TranslationYAnimation.fillMode = fillMode;
	whitePuff13TranslationYAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff13"] layer] addAnimation:whitePuff13TranslationYAnimation forKey:@"explode_TranslationY"];

	CAKeyframeAnimation *plusOneOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	plusOneOpacityAnimation.duration = 1.000;
	plusOneOpacityAnimation.values = @[@(0.000), @(1.000), @(0.000)];
	plusOneOpacityAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	plusOneOpacityAnimation.timingFunctions = @[linearTiming, linearTiming];
	plusOneOpacityAnimation.beginTime = beginTime;
	plusOneOpacityAnimation.fillMode = fillMode;
	plusOneOpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"plusOne"] layer] addAnimation:plusOneOpacityAnimation forKey:@"explode_Opacity"];

	CAKeyframeAnimation *plusOneScaleXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.x"];
	plusOneScaleXAnimation.duration = 1.000;
	plusOneScaleXAnimation.values = @[@(0.210), @(1.010), @(0.210)];
	plusOneScaleXAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	plusOneScaleXAnimation.timingFunctions = @[linearTiming, linearTiming];
	plusOneScaleXAnimation.beginTime = beginTime;
	plusOneScaleXAnimation.fillMode = fillMode;
	plusOneScaleXAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"plusOne"] layer] addAnimation:plusOneScaleXAnimation forKey:@"explode_ScaleX"];

	CAKeyframeAnimation *plusOneScaleYAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.y"];
	plusOneScaleYAnimation.duration = 1.000;
	plusOneScaleYAnimation.values = @[@(0.210), @(1.010), @(0.210)];
	plusOneScaleYAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	plusOneScaleYAnimation.timingFunctions = @[linearTiming, linearTiming];
	plusOneScaleYAnimation.beginTime = beginTime;
	plusOneScaleYAnimation.fillMode = fillMode;
	plusOneScaleYAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"plusOne"] layer] addAnimation:plusOneScaleYAnimation forKey:@"explode_ScaleY"];

	CAKeyframeAnimation *whitePuff12RotationAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.rotation.z"];
	whitePuff12RotationAnimation.duration = 1.000;
	whitePuff12RotationAnimation.values = @[@(0.000), @(-0.588), @(0.000)];
	whitePuff12RotationAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff12RotationAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff12RotationAnimation.beginTime = beginTime;
	whitePuff12RotationAnimation.fillMode = fillMode;
	whitePuff12RotationAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff12"] layer] addAnimation:whitePuff12RotationAnimation forKey:@"explode_Rotation"];

	CAKeyframeAnimation *whitePuff12OpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	whitePuff12OpacityAnimation.duration = 1.000;
	whitePuff12OpacityAnimation.values = @[@(0.000), @(1.000), @(0.000)];
	whitePuff12OpacityAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff12OpacityAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff12OpacityAnimation.beginTime = beginTime;
	whitePuff12OpacityAnimation.fillMode = fillMode;
	whitePuff12OpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff12"] layer] addAnimation:whitePuff12OpacityAnimation forKey:@"explode_Opacity"];

	CAKeyframeAnimation *whitePuff12ScaleXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.x"];
	whitePuff12ScaleXAnimation.duration = 1.000;
	whitePuff12ScaleXAnimation.values = @[@(-0.010), @(0.350), @(-0.010)];
	whitePuff12ScaleXAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff12ScaleXAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff12ScaleXAnimation.beginTime = beginTime;
	whitePuff12ScaleXAnimation.fillMode = fillMode;
	whitePuff12ScaleXAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff12"] layer] addAnimation:whitePuff12ScaleXAnimation forKey:@"explode_ScaleX"];

	CAKeyframeAnimation *whitePuff12ScaleYAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.y"];
	whitePuff12ScaleYAnimation.duration = 1.000;
	whitePuff12ScaleYAnimation.values = @[@(-0.010), @(0.350), @(-0.010)];
	whitePuff12ScaleYAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff12ScaleYAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff12ScaleYAnimation.beginTime = beginTime;
	whitePuff12ScaleYAnimation.fillMode = fillMode;
	whitePuff12ScaleYAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff12"] layer] addAnimation:whitePuff12ScaleYAnimation forKey:@"explode_ScaleY"];

	CAKeyframeAnimation *whitePuff11RotationAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.rotation.z"];
	whitePuff11RotationAnimation.duration = 1.000;
	whitePuff11RotationAnimation.values = @[@(0.000), @(0.852), @(0.000)];
	whitePuff11RotationAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff11RotationAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff11RotationAnimation.beginTime = beginTime;
	whitePuff11RotationAnimation.fillMode = fillMode;
	whitePuff11RotationAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff11"] layer] addAnimation:whitePuff11RotationAnimation forKey:@"explode_Rotation"];

	CAKeyframeAnimation *whitePuff11OpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	whitePuff11OpacityAnimation.duration = 1.000;
	whitePuff11OpacityAnimation.values = @[@(0.000), @(1.000), @(0.000)];
	whitePuff11OpacityAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff11OpacityAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff11OpacityAnimation.beginTime = beginTime;
	whitePuff11OpacityAnimation.fillMode = fillMode;
	whitePuff11OpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff11"] layer] addAnimation:whitePuff11OpacityAnimation forKey:@"explode_Opacity"];

	CAKeyframeAnimation *whitePuff11ScaleXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.x"];
	whitePuff11ScaleXAnimation.duration = 1.000;
	whitePuff11ScaleXAnimation.values = @[@(0.000), @(0.580), @(0.000)];
	whitePuff11ScaleXAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff11ScaleXAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff11ScaleXAnimation.beginTime = beginTime;
	whitePuff11ScaleXAnimation.fillMode = fillMode;
	whitePuff11ScaleXAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff11"] layer] addAnimation:whitePuff11ScaleXAnimation forKey:@"explode_ScaleX"];

	CAKeyframeAnimation *whitePuff11ScaleYAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.y"];
	whitePuff11ScaleYAnimation.duration = 1.000;
	whitePuff11ScaleYAnimation.values = @[@(0.000), @(0.580), @(0.000)];
	whitePuff11ScaleYAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff11ScaleYAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff11ScaleYAnimation.beginTime = beginTime;
	whitePuff11ScaleYAnimation.fillMode = fillMode;
	whitePuff11ScaleYAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff11"] layer] addAnimation:whitePuff11ScaleYAnimation forKey:@"explode_ScaleY"];

	CAKeyframeAnimation *whitePuff10RotationAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.rotation.z"];
	whitePuff10RotationAnimation.duration = 1.000;
	whitePuff10RotationAnimation.values = @[@(0.000), @(0.000)];
	whitePuff10RotationAnimation.keyTimes = @[@(0.000), @(1.000)];
	whitePuff10RotationAnimation.timingFunctions = @[linearTiming];
	whitePuff10RotationAnimation.beginTime = beginTime;
	whitePuff10RotationAnimation.fillMode = fillMode;
	whitePuff10RotationAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff10"] layer] addAnimation:whitePuff10RotationAnimation forKey:@"explode_Rotation"];

	CAKeyframeAnimation *whitePuff10OpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	whitePuff10OpacityAnimation.duration = 1.000;
	whitePuff10OpacityAnimation.values = @[@(0.000), @(1.000), @(0.000)];
	whitePuff10OpacityAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff10OpacityAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff10OpacityAnimation.beginTime = beginTime;
	whitePuff10OpacityAnimation.fillMode = fillMode;
	whitePuff10OpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff10"] layer] addAnimation:whitePuff10OpacityAnimation forKey:@"explode_Opacity"];

	CAKeyframeAnimation *whitePuff10ScaleXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.x"];
	whitePuff10ScaleXAnimation.duration = 1.000;
	whitePuff10ScaleXAnimation.values = @[@(0.000), @(0.510), @(0.000)];
	whitePuff10ScaleXAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff10ScaleXAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff10ScaleXAnimation.beginTime = beginTime;
	whitePuff10ScaleXAnimation.fillMode = fillMode;
	whitePuff10ScaleXAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff10"] layer] addAnimation:whitePuff10ScaleXAnimation forKey:@"explode_ScaleX"];

	CAKeyframeAnimation *whitePuff10ScaleYAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.y"];
	whitePuff10ScaleYAnimation.duration = 1.000;
	whitePuff10ScaleYAnimation.values = @[@(0.000), @(0.510), @(0.000)];
	whitePuff10ScaleYAnimation.keyTimes = @[@(0.000), @(0.500), @(1.000)];
	whitePuff10ScaleYAnimation.timingFunctions = @[linearTiming, linearTiming];
	whitePuff10ScaleYAnimation.beginTime = beginTime;
	whitePuff10ScaleYAnimation.fillMode = fillMode;
	whitePuff10ScaleYAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"whitePuff10"] layer] addAnimation:whitePuff10ScaleYAnimation forKey:@"explode_ScaleY"];
}

- (void)removeExplodeAnimation
{
	[self.layer removeAnimationForKey:@"Explode"];
	[[self.viewsByName[@"whitePuff13"] layer] removeAnimationForKey:@"explode_Rotation"];
	[[self.viewsByName[@"whitePuff13"] layer] removeAnimationForKey:@"explode_Opacity"];
	[[self.viewsByName[@"whitePuff13"] layer] removeAnimationForKey:@"explode_ScaleX"];
	[[self.viewsByName[@"whitePuff13"] layer] removeAnimationForKey:@"explode_ScaleY"];
	[[self.viewsByName[@"whitePuff13"] layer] removeAnimationForKey:@"explode_TranslationX"];
	[[self.viewsByName[@"whitePuff13"] layer] removeAnimationForKey:@"explode_TranslationY"];
	[[self.viewsByName[@"plusOne"] layer] removeAnimationForKey:@"explode_Opacity"];
	[[self.viewsByName[@"plusOne"] layer] removeAnimationForKey:@"explode_ScaleX"];
	[[self.viewsByName[@"plusOne"] layer] removeAnimationForKey:@"explode_ScaleY"];
	[[self.viewsByName[@"whitePuff12"] layer] removeAnimationForKey:@"explode_Rotation"];
	[[self.viewsByName[@"whitePuff12"] layer] removeAnimationForKey:@"explode_Opacity"];
	[[self.viewsByName[@"whitePuff12"] layer] removeAnimationForKey:@"explode_ScaleX"];
	[[self.viewsByName[@"whitePuff12"] layer] removeAnimationForKey:@"explode_ScaleY"];
	[[self.viewsByName[@"whitePuff11"] layer] removeAnimationForKey:@"explode_Rotation"];
	[[self.viewsByName[@"whitePuff11"] layer] removeAnimationForKey:@"explode_Opacity"];
	[[self.viewsByName[@"whitePuff11"] layer] removeAnimationForKey:@"explode_ScaleX"];
	[[self.viewsByName[@"whitePuff11"] layer] removeAnimationForKey:@"explode_ScaleY"];
	[[self.viewsByName[@"whitePuff10"] layer] removeAnimationForKey:@"explode_Rotation"];
	[[self.viewsByName[@"whitePuff10"] layer] removeAnimationForKey:@"explode_Opacity"];
	[[self.viewsByName[@"whitePuff10"] layer] removeAnimationForKey:@"explode_ScaleX"];
	[[self.viewsByName[@"whitePuff10"] layer] removeAnimationForKey:@"explode_ScaleY"];
}

- (void)animationDidStop:(CAAnimation *)anim finished:(BOOL)flag
{
	void (^completion)(BOOL) = [self.completionBlocksByAnimation objectForKey:anim];
	[self.completionBlocksByAnimation removeObjectForKey:anim];
	if (completion)
	{
		completion(flag);
	}
}

- (void)removeAllAnimations
{
	for (UIView *view in self.viewsByName.allValues)
	{
		[view.layer removeAllAnimations];
	}
	[self.layer removeAnimationForKey:@"Explode"];
}

@end